(define (linear-equation a11 a12 a21 a22 b1 b2)
  (let* ((new-y1 (/ a12 a11))
         (new-b1 (/ b1 a11))
         (new-y2 (/ a22 a21))
         (new-b2 (/ b2 a21))
         (diff-y (- new-y2 new-y1))
         (diff-b (- new-b2 new-b1))
         )
    (if (equal? diff-y 0)
        '()
        (let* ((y-ans (/ diff-b diff-y))
               (x-ans (- new-b1 (* new-y1 y-ans)))
               )
          (list x-ans y-ans))
        )
    )
  )
